[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "invalid-name", 
    "redefined-builtin"
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true