datasets:
  car:
    column_mapping:
      categorical_features:
        # - 'Gender'
      numerical_features:
        - 'Age'
        - 'AnnualSalary'
      target: 
        - 'Purchased'
    data_format:
      header: true
      separator: ','
    monitors:
      # - data_drift
      - classification_performance
      - cat_target_drift
    reference_file: ./datasets/car_data.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
