name: CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push
      working-directory: 'final_project/src'
      run: docker-compose build
           docker tag car-prediction:latest "$DOCKER_USERNAME"/car-prediction:latest
           docker-compose push "$DOCKER_USERNAME"/car-prediction:latest
